changes to config, cleanup and sort facecolors hash

diff --git a/install b/install
--- a/install
+++ b/install
@@ -135,8 +135,13 @@ function _setup_etc_profile_()
 # source bash-color-tools libraries
 # for prompt and _face() usage
 BCT=${inst_prefix}/share/bash-color-tools/libexec
-if [[ -f \${BCT}/face && -f \${BCT}/prompt ]]; then
+if [[ -d \${BCT} \\
+    && -f \${BCT}/face \\
+    && -f \${BCT}/prompt \\
+    && -f \${BCT}/facecolors.rgb ]]; then
+
     # source bash-color-tools libs
+    source \${BCT}/facecolors.rgb
     source \${BCT}/face libmode
     source \${BCT}/prompt
 fi
@@ -153,22 +158,37 @@ function _setup_bashrc_()
 {
     local inst_prefix=${1}
 
-    [[ $(grep 'source.*/face\ libmode' ~/.bashrc) ]] || {
-        cat >> ~/.bashrc <<EOF
+    cat > ~/.bctrc <<EOF
 #
 # source bash-color-tools libraries
 # for prompt and _face() usage
 BCT=${inst_prefix}/share/bash-color-tools/libexec
-if [[ -f \${BCT}/face && -f \${BCT}/prompt ]]; then
+if [[ -d \${BCT} \\
+    && -f \${BCT}/face \\
+    && -f \${BCT}/prompt \\
+    && -f \${BCT}/facecolors.rgb ]]; then
+
     # source bash-color-tools libs
+    source \${BCT}/facecolors.rgb
     source \${BCT}/face libmode
     source \${BCT}/prompt
+
+else
+    echo "Error: \${BCT}/ and/or specific files within it are missing..."
+    echo "Is bash-color-tools actually installed?"
+    echo "If not, remove or comment out the 'source ~/.bctrc' code from your ~/.bashrc"
 fi
-# uncomment and select the theme you want here
-# to have prompt autostart with each shell
-#prompt git
+
+# use 'prompt save' to save current theme to autostart.
+prompt progit
 
 EOF
+
+    [[ $(grep 'source.*bctrc' ~/.bashrc) ]] || {
+        echo "" >>~/.bashrc
+        echo "# initialize bash-color-tools prompt code" >>~/.bashrc
+        echo "source ~/.bctrc" >>~/.bashrc
+
     }
 }
 
@@ -211,7 +231,7 @@ case ${0##*/} in
     install)
         _verify_permissions_ ${PREFIX} || {
             echo "Oops! you do not have permission to install into ${PREFIX}."
-            echo "use sudo, or: 'PREFIX=/some/other/dir ./install' for non-privileged installations"
+            echo "use sudo, or: 'PREFIX=/a/dir/you/own ./install' for non-privileged installations"
             exit 1
         }
         [[ "${0}" =~ ${PREFIX} ]] && { echo "uninstall, then install from the original package."; exit 1; }
@@ -250,4 +270,3 @@ case ${0##*/} in
         ;;
 
 esac
-
diff --git a/src/libexec/functions b/src/libexec/functions
--- a/src/libexec/functions
+++ b/src/libexec/functions
@@ -166,25 +166,41 @@ function prompt_theme_list()
 }
 
 #-------------------------------------------------------------------------------
-function prompt_save_to_bashrc()
+function prompt_save_to_bctrc()
 {
     local inst_prefix=$(echo ${THEME_DIR} | sed 's,/share/bash-color-tools/themes,,')
 
-    [[ $(grep 'source.*/face\ libmode' ~/.bashrc) ]] || {
-        cat >> ~/.bashrc <<EOF
+    cat > ~/.bctrc <<EOF
 #
 # source bash-color-tools libraries
 # for prompt and _face() usage
 BCT=${inst_prefix}/share/bash-color-tools/libexec
-if [[ -f \${BCT}/face && -f \${BCT}/prompt ]]; then
+if [[ -d \${BCT} \\
+    && -f \${BCT}/face \\
+    && -f \${BCT}/prompt \\
+    && -f \${BCT}/facecolors.rgb ]]; then
+
     # source bash-color-tools libs
+    source \${BCT}/facecolors.rgb
     source \${BCT}/face libmode
     source \${BCT}/prompt
+
+else
+    echo "Error: \${BCT}/ and/or specific files within it are missing..."
+    echo "Is bash-color-tools actually installed?"
+    echo "If not, remove or comment out the 'source ~/.bctrc' code from your ~/.bashrc"
 fi
-#prompt builtin
+
+# use 'prompt save' to save current theme to autostart.
+prompt ${THEME:-builtin}
 
 EOF
-    }
-    sed -i "s,^[ #]*prompt[[:blank:]][-a-zA-Z0-9._]*$,prompt ${THEME:-builtin},"  ~/.bashrc
-}
 
+    # make sure it's getting included at startup
+    [[ $(grep 'source.*bctrc' ~/.bashrc) ]] || {
+        echo "" >>~/.bashrc
+        echo "# initialize bash-color-tools prompt code" >>~/.bashrc
+        echo "source ~/.bctrc" >>~/.bashrc
+
+    }
+}
diff --git a/src/libexec/prompt b/src/libexec/prompt
--- a/src/libexec/prompt
+++ b/src/libexec/prompt
@@ -41,7 +41,7 @@ function prompt()
 {
     (( ${#} == 0 )) && {
         echo "Usage: prompt <theme_name|list|save>"
-        echo "'prompt save' to modify ~/.bashrc to autostart current theme"
+        echo "'prompt save' to modify ~/.bctrc to autostart current theme"
         return 1
     }
 
@@ -63,8 +63,8 @@ function prompt()
             ;;
 
         save)
-            prompt_save_to_bashrc || {
-                echo "unable to save settings to ~/.bashrc"
+            prompt_save_to_bctrc || {
+                echo "unable to save settings to ~/.bctrc"
                 return 1
             }
             echo "theme '${THEME:-builtin}' is set to autostart"
