refactor face help file access depending on PREFIX

diff --git a/install b/install
--- a/install
+++ b/install
@@ -124,6 +124,14 @@ function _set_themes_dir_()
 }
 
 #-------------------------------------------------------------------------------
+function _set_man_dir_()
+{
+    local inst_prefix=${1}
+    sed -i "s,^PREFIX=.*$,PREFIX==${inst_prefix}/share," \
+        ${inst_prefix}/share/bash-color-tools/libexec/face || return 1
+}
+
+#-------------------------------------------------------------------------------
 function _setup_etc_profile_()
 {
     local inst_prefix=${1}
@@ -238,6 +246,7 @@ case ${0##*/} in
         _install_ ${PREFIX} || { echo "installation failed."; exit 1; }
         _install_links_ ${PREFIX} || { echo "installation of links failed."; exit 1; }
         _set_themes_dir_ ${PREFIX} || { echo "configuring prompt themes directory failed."; exit 1; }
+        _set_man_dir_ ${PREFIX} || { echo "configuring face man directory failed."; exit 1; }
         _setup_etc_profile_ ${PREFIX} || {
             echo "permissions prevent installing global settings in:"
             echo "/etc/profile.d/bash-color-tools.sh"
diff --git a/src/libexec/face b/src/libexec/face
--- a/src/libexec/face
+++ b/src/libexec/face
@@ -32,7 +32,7 @@ LICENSE
     exit 1
 }
 
-PREFIX=/usr/share/bash-color-tools
+PREFIX=/usr/share
 
 #-------------------------------------------------------------------------------
 # Usage
@@ -57,12 +57,12 @@ function face_usage()
 }
 function face_help()
 {
-    [[ -f ../../doc/bash-color-tools/man/face ]] && {
-        less ../../doc/bash-color-tools/man/face
+    [[ -f ${PREFIX}/doc/bash-color-tools/man/face ]] && {
+        less ${PREFIX}/doc/bash-color-tools/man/face
     } || {
         echo >&2 "Full help file missing."
-        echo >&2 "\${INSTALL_PREFIX}/doc/bash-color-tools/man/face not found."
-        face_help
+        echo >&2 "${PREFIX}/doc/bash-color-tools/man/face not found."
+        face_usage
     }
 }
 
@@ -262,7 +262,7 @@ case "${1}" in
     libmode)
         export -f _face
         [[ ${FACECOLORS[salmon]} ]] || {
-            source ${PREFIX}/libexec/facecolors.rgb
+            source ${PREFIX}/bash-color-tools/libexec/facecolors.rgb
         }
         ;;
 
