new face input types

diff --git a/src/libexec/face b/src/libexec/face
--- a/src/libexec/face
+++ b/src/libexec/face
@@ -36,12 +36,32 @@ LICENSE
 # Usage
 function face_usage()
 {
-    echo >&2 "Usage:"
-    echo >&2 " ${0##*/} [<[OPTS] \"string\">|[libmode|colors]]"
-    echo >&2 " use: '${0##*/} -H' for color echo command usage"
-    echo >&2 " use: 'source /path/to/${0##*/} libmode' to use _face function in scripts"
-    echo >&2 " use: '${0##*/} [-v] colors' to print color pallettes and their rgb values"
-    return 0
+    echo >&2 "USAGE:"
+    echo >&2 " face <[OPTS] 'string'>|<libmode>|<[-v] colors>"
+    echo >&2
+    echo >&2 " face <-h|-H>"
+    echo >&2
+    echo >&2 " face <[-P] [-l] [-n] [-e] \\"
+    echo >&2 "           [-f <color-name>|<face-rgb>|<hex-rgb>|<dec-rgb>] \\"
+    echo >&2 "           [-b <color-name>|<face-rgb>|<hex-rgb>|<dec-rgb>] 'message'>"
+    echo >&2
+    echo >&2 " face <[-v] colors>"
+    echo >&2
+    echo >&2 " source /path/to/face <libmode>"
+    echo >&2
+    echo >&2 " use: 'face -h and -H' for color echo command help and usage"
+    echo >&2 " use: 'source /path/to/face libmode' to use _face function in scripts"
+    echo >&2 " use: 'face [-v] colors' to print color pallettes, and optionally their rgb values"
+}
+function face_help()
+{
+    [[ -f ../../doc/bash-color-tools/man/face ]] && {
+        less ../../doc/bash-color-tools/man/face
+    } || {
+        echo >&2 "Full help file missing."
+        echo >&2 "\${INSTALL_PREFIX}/doc/bash-color-tools/man/face not found."
+        face_help
+    }
 }
 
 #-------------------------------------------------------------------------------
@@ -49,85 +69,40 @@ function face_usage()
 function _face()
 {
     OPTIND=
-    while getopts ":PHhlnef:b:" opt
+    while getopts ":HPb:ef:hln" opt
     do
         case ${opt} in
-            n) local N=n               ;; # no newline
-            e) local E=e               ;; # escape message
-            f) local -l F=${OPTARG:-x} ;; # foreground rgb
-            b) local -l B=${OPTARG:-x} ;; # background rgb
+            H) face_help;  exit 1      ;; # verbose help
+            P) local PS1_mode=1        ;; # use additional escapes for prompt mode
+            b) local -l bg_color=${OPTARG:-x} ;; # background color rgb/name
+            e) local E=e               ;; # process escapes codes in the  message
+            f) local -l fg_color=${OPTARG:-x} ;; # foreground color rgb/name
+            h) face_usage; exit 1      ;; # basic help
             l) local mode=lowcolor     ;; # low-color mode
-            P) local pmode=1           ;; # use additional escapes for prompt mode
-            H)                            # help
-                echo >&2 "USAGE: ${0##*/} [-h|-H] | [-P] [-l] [-n] [-e] [-f rgb] [-b rgb] \"message\""
-                echo >&2 "where r,g, and b are values between 1 and 5 inclusive"
-                echo >&2 "for example, ${0##*/} -f 555 -b 500 \" here is my message \" produces..."
-                ${0##*/} -f 555 -b 500 " here is my message "
-                echo >&2
-                echo >&2 "Or in low color mode for consoles..."
-                echo >&2 "${0##*/} -lf <fgnd_colorname> -b <bgnd_colorname> \"message\""
-                echo >&2 "where colorname is one of: white, black, red, green, blue, yellow, purple and gray"
-                echo >&2 "foreground colors can also use the 'bright' prefix modifier, as in 'brightred'"
-                echo >&2 "for example, ${0##*/} -lf white -b red \" here is my message \" produces..."
-                ${0##*/} -lf white -b red " here is my message "
-                echo >&2
-                echo >&2 "Note: use '-P' to generate specially escaped strings for \$PS1"
-                echo >&2
-                return 1
-                ;;
-            h) echo >&2 "USAGE: ${0##*/} [ [-h|-H] | [-P] [-l] [-n] [-e] [-f rgb] [-b rgb] \"message\" ]"; return 1 ;;
-            *) : ;;
+            n) local N=n               ;; # no newline
+            *) : ;; # process commands
         esac
     done
-    shift $((${OPTIND}-1))
 
-    # hicolor w/ rgb is the default mode
-    mode=${mode:-hicolor}
+    # reset to normal
+    shift $((${OPTIND}-1))
+    [[ ${PS1_mode} ]] && {
+        # for PS1
+        local norm="\[\033[0m\]"; echo -n "${norm}"
+    } || {
+        # for color echoing
+        local norm="\033[0m"; echo -ne "${norm}"
+    }
+
     case ${mode} in
 
-        hicolor)
-            [[ ${pmode} ]] && {
-                # for PS1
-                local norm="\[\033[0m\]"
-            } || {
-                # for color echoing
-                local norm="\033[0m"
-            }
-            local -A C=(); C=( [white]=555 [red]=500 [green]=050 [blue]=005 [black]=000 [none]="${norm}" ) # TODO: match lowcolor names
-            local -A g=(); g=( [F]=3 [B]=4 )
+        lowcolor) # low-color mode: console mode w/o framebuffer requires this mode [-l]
 
-            function rgb2idx() { echo -n "$((16+${1:0:1}*36+${1:1:1}*6+${1:2:1}))m"; }
+            [[ ${PS1_mode} ]] && {
 
-            function color()
-            {
-                [[ ${pmode} ]] && {
-                    # for PS1
-                    echo -n "\[\033[${1}8;5;$(rgb2idx ${2})\]"
-                } || {
-                    # for color echoing
-                    echo -ne "\033[${1}8;5;$(rgb2idx ${2})"
-                }
-            }
-
-            # setup colors for next print
-            for i in ${F} ${B}
-            do
-                # rgb
-                [[ ${i} =~ ^[0-5]{3}$  ]] \
-                    && { [[ ${i} == ${F} ]] && color ${g[F]} ${F} || color ${g[B]} ${B}; }
-                # named color
-                [[ "${!C[@]}" =~ ${i} ]] \
-                    && { [[ ${i} == ${F} ]] && color ${g[F]} ${C[${i}]} || color ${g[B]} ${C[${i}]}; }
-            done
-            ;;
-
-        lowcolor) # console mode w/o framebuffer requires this mode [-l]
-            [[ ${pmode} ]] && {
-                # for PS1
-                # saved norm prefix \033[0;0;40m
-                local norm="\[\033[0m\]"; echo -n "${norm}"
+                # for PS1 prompt strings
                 # forground
-                local -A fC=(); fC=(
+                local -A foreground_color_names=(
                     [white]='\[\033[1;37m\]'  [black]='\[\033[0;30m\]'
                     [gray]='\[\033[1;30m\]'   [brightgray]='\[\033[0;37m\]'
                     [red]='\[\033[0;31m\]'    [brightred]='\[\033[1;31m\]'
@@ -139,62 +114,119 @@ function _face()
                     [none]='\[\033[0;37m\]'
                 )
                 # background
-                local -A bC=(); bC=(
+                local -A background_color_names=(
                     [white]='\[\033[47m\]'    [black]='\[\033[40m\]'
                     [red]='\[\033[41m\]'      [green]='\[\033[42m\]'
                     [yellow]='\[\033[43m\]'   [blue]='\[\033[44m\]'
                     [purple]='\[\033[45m\]'   [cyan]='\[\033[46m\]'
                     [none]='\[\033[40m\]'
                 )
+
             } || {
+
                 # for color echoing
-                # saved norm prefix \033[0;0;40m
-                local norm="\033[0m"; echo -ne "${norm}"
                 # forground
-                local -A fC=(); fC=(
-                    [white]='\033[1;37m'  [black]='\033[0;30m'
-                    [gray]='\033[1;30m'   [brightgray]='\033[0;37m'
-                    [red]='\033[0;31m'    [brightred]='\033[1;31m'
-                    [green]='\033[0;32m'  [brightgreen]='\033[1;32m'
-                    [yellow]='\033[0;33m' [brightyellow]='\033[1;33m'
-                    [blue]='\033[0;34m'   [brightblue]='\033[1;34m'
-                    [purple]='\033[0;35m' [brightpurple]='\033[1;35m'
-                    [cyan]='\033[0;36m'   [brightcyan]='\033[1;36m'
+                local -A foreground_color_names=(
+                    [white]='\033[1;37m'      [black]='\033[0;30m'
+                    [gray]='\033[1;30m'       [brightgray]='\033[0;37m'
+                    [red]='\033[0;31m'        [brightred]='\033[1;31m'
+                    [green]='\033[0;32m'      [brightgreen]='\033[1;32m'
+                    [yellow]='\033[0;33m'     [brightyellow]='\033[1;33m'
+                    [blue]='\033[0;34m'       [brightblue]='\033[1;34m'
+                    [purple]='\033[0;35m'     [brightpurple]='\033[1;35m'
+                    [cyan]='\033[0;36m'       [brightcyan]='\033[1;36m'
                     [none]='\033[0;37m'
                 )
                 # background
-                local -A bC=(); bC=(
-                    [white]='\033[47m'    [black]='\033[40m'
-                    [red]='\033[41m'      [green]='\033[42m'
-                    [yellow]='\033[43m'   [blue]='\033[44m'
-                    [purple]='\033[45m'   [cyan]='\033[46m'
+                local -A background_color_names=(
+                    [white]='\033[47m'        [black]='\033[40m'
+                    [red]='\033[41m'          [green]='\033[42m'
+                    [yellow]='\033[43m'       [blue]='\033[44m'
+                    [purple]='\033[45m'       [cyan]='\033[46m'
                     [none]='\033[40m'
                 )
             }
-            [[ ${F} ]] && [[ "${!fC[@]}" =~ "${F}" ]] && fg="${fC[${F}]}"
-            [[ ${B} ]] && [[ "${!bC[@]}" =~ "${B}" ]] && bg="${bC[${B}]}"
-            [[ ${B} ]] || bg="${bC[none]}"
-            # setup colors for next print
-            [[ ${pmode} ]] && {
+
+            [[ ${fg_color} ]] && [[ "${!foreground_color_names[@]}" =~ (^|[\ ]*)${fg_color}($|[\ ]*) ]] && fg="${foreground_color_names[${fg_color}]}"
+            [[ ${bg_color} ]] && [[ "${!background_color_names[@]}" =~ (^|[\ ]*)${bg_color}($|[\ ]*) ]] && bg="${background_color_names[${bg_color}]}"
+            [[ ${bg_color} ]] || bg="${background_color_names[none]}"
+
+            # setup low colors for next print
+            [[ ${PS1_mode} ]] && {
                 # for PS1
                 echo -n "${fg}${bg}"
             } || {
                 # for color echoing
                 echo -ne "${fg}${bg}"
             }
+
             ;;
+
+        *) #-------------------------------------------------------------------------------
+           # default high-color mode: requires an xterm or framebuffer
+
+            # check for the globally sourced color name hash
+            [[ ${FACECOLORS} ]] || {
+                # otherwise, load minimal set
+                local -A FACECOLORS=( [white]=555 [red]=500 [green]=050 [blue]=005 [black]=000 [none]="${norm}" )
+            }
+
+            function hex2rgb() { :; }
+
+            function dec2rgb() { :; }
+
+            function convert2rgb()
+            {
+                local colorid=${1}
+                # already in face rgb format, return
+                [[ ${colorid} =~ ^[0-5]{3}$ ]] && { echo ${colorid}; return 0; }
+                # in hex format, convert
+                [[ ${colorid} =~ ^[0-9a-f]{6}$ ]] && { hex2rgb ${colorid}; return 0; }
+                # in decimal format, convert
+                [[ ${colorid} =~ ^[0-2][0-5]{2},[0-2][0-5]{2},[0-2][0-5]{2} ]] && { dec2rgb ${colorid}; return 0; }
+                # in color name format, get from hash
+                [[ "${!FACECOLORS[@]}" =~ (^|[\ ]*)${colorid}($|[\ ]*) ]] && { echo ${FACECOLORS[${colorid}]}; return 0; }
+            }
+
+            function rgb2idx() { echo -n "$((16+${1:0:1}*36+${1:1:1}*6+${1:2:1}))m"; }
+
+            function color()
+            {
+                [[ ${PS1_mode} ]] && {
+                    # for PS1
+                    echo -n "\[\033[${1}8;5;$(rgb2idx ${2})\]"
+                } || {
+                    # for color echoing
+                    echo -ne "\033[${1}8;5;$(rgb2idx ${2})"
+                }
+            }
+
+            # setup high colors for next print
+            local fg_idx=3 bg_idx=4
+            [[ ${fg_color} ]] && color ${fg_idx} $(convert2rgb ${fg_color})
+            [[ ${bg_color} ]] && color ${bg_idx} $(convert2rgb ${bg_color})
+
+            ;;
+
     esac
 
+    #---------------------------------------------------------------------------
+    # print the text
     echo -n ${E:+ -${E}} "${*}"
-    [[ ${pmode} ]] && {
+
+    #---------------------------------------------------------------------------
+    # reset to normal
+    [[ ${PS1_mode} ]] && {
         # for PS1
         echo ${N:+ -${N}} "${norm}"
     } || {
         # for color echoing
         echo -e ${N:+ -${N}} "${norm}"
     }
+
     return 0
 }
+
 
 #===============================================================================
 # use as lib, color pallette demo, or simple colorizing echo command
